import assert from 'node:assert/strict';
import {classifyCommand,expand} from './core.mjs';
import {handleMcp,tools} from './mcp.mjs';
import {sandboxCapabilities,macProfile} from './sandbox.mjs';
import {classifyExec,cleanEnv} from './executor.mjs';
import {issueWorkspaceCapability,verifyWorkspaceCapability} from './capability.mjs';
import {requestApproval,listApprovals,decideApproval,consumeDecision} from './approvals.mjs';
assert.equal(classifyCommand('git status'),'safe');
assert.equal(classifyCommand('npm test'),'safe');
assert.equal(classifyCommand('rm -rf dist'),'destructive');
assert.equal(classifyCommand('sudo reboot'),'destructive');
assert.equal(classifyCommand('npm install'),'write');
assert.ok(expand('~/Developer').startsWith('/'));
assert.ok(tools.length>=8);
const init=await handleMcp({jsonrpc:'2.0',id:1,method:'initialize',params:{}});
assert.equal(init.result.serverInfo.name,'codebridge');
const listed=await handleMcp({jsonrpc:'2.0',id:2,method:'tools/list',params:{}});
assert.ok(listed.result.tools.length<tools.length);assert.ok(listed.result.tools.every(t=>!['write_file','run_command','run_legacy_shell','create_safe_workspace'].includes(t.name)));
const profile=macProfile('/tmp/codebridge-test');assert.ok(profile.includes('(deny default)'));assert.ok(profile.includes('/tmp/codebridge-test'));
const sb=await sandboxCapabilities();assert.ok(typeof sb.available==='boolean');
const cap=await issueWorkspaceCapability({workspace:'/tmp/project',executable:'git',args:['status']});const capData=await verifyWorkspaceCapability(cap);assert.equal(capData.workspace,'/tmp/project');await assert.rejects(()=>verifyWorkspaceCapability(cap));const tampered=await issueWorkspaceCapability({workspace:'/tmp/project',executable:'git',args:['status']});const [tb,tsig]=tampered.split('.');const flip=tsig[0]==='A'?'B':'A';await assert.rejects(()=>verifyWorkspaceCapability(`${tb}.${flip}${tsig.slice(1)}`));
const approval=requestApproval({type:'command',cwd:'/tmp/project',executable:'python3',args:['x.py']});assert.ok(listApprovals().some(x=>x.id===approval.id));decideApproval(approval.id,true);assert.equal(consumeDecision(approval.id).status,'approved');assert.equal(consumeDecision(approval.id),null);
assert.equal(classifyExec('git',['status']),'safe');assert.equal(classifyExec('git',['reset','--hard']),'destructive');assert.equal(classifyExec('sudo',['ls']),'blocked');assert.equal(classifyExec('python3',['x.py']),'approval');assert.equal(cleanEnv().OPENAI_API_KEY,undefined);
console.log('CodeBridge core + optional MCP + sandbox security tests passed.');
