import {getConfig,listWorkspace,readText,writeText,runCommand,runStructuredCommand,gitInfo} from './core.mjs';
import {createSafeWorkspace,reviewSafeWorkspace} from './worktrees.mjs';
import {requestApproval,consumeDecision} from './approvals.mjs';
import {openWorkspace,listOpenWorkspaces} from './workspaces.mjs';
import {getAccessMode,toolAllowed} from './capabilities.mjs';

export const tools=[
 {name:'open_workspace',description:'Open an allowed project for this conversation and return applicable project instructions.',inputSchema:{type:'object',required:['path'],properties:{path:{type:'string'},mode:{type:'string',enum:['checkout','worktree']},baseRef:{type:'string'}}}},
 {name:'list_open_workspaces',description:'List workspaces opened in this CodeBridge session.',inputSchema:{type:'object',properties:{}}},
 {name:'list_projects',description:'List project folders explicitly allowed by the user.',inputSchema:{type:'object',properties:{}}},
 {name:'list_files',description:'List files in an allowed folder.',inputSchema:{type:'object',required:['path'],properties:{path:{type:'string'}}}},
 {name:'read_file',description:'Read a UTF-8 text file in an allowed project.',inputSchema:{type:'object',required:['path'],properties:{path:{type:'string'}}}},
 {name:'write_file',description:'Write a UTF-8 text file in an allowed project.',inputSchema:{type:'object',required:['path','content'],properties:{path:{type:'string'},content:{type:'string'}}}},
 {name:'run_command',description:'Run a structured executable with arguments in an allowed project. Commands outside the safe policy require approval.',inputSchema:{type:'object',required:['cwd','executable'],properties:{cwd:{type:'string'},executable:{type:'string'},args:{type:'array',items:{type:'string'}},approvalId:{type:'string'}}}},
 {name:'run_legacy_shell',description:'Developer-mode compatibility tool for free-form shell. Always requires explicit approval.',inputSchema:{type:'object',required:['cwd','command'],properties:{cwd:{type:'string'},command:{type:'string'},approved:{type:'boolean'}}}},
 {name:'git_status',description:'Inspect Git branch and working tree state.',inputSchema:{type:'object',required:['path'],properties:{path:{type:'string'}}}},
 {name:'create_safe_workspace',description:'Create an isolated Git worktree for an AI coding task.',inputSchema:{type:'object',required:['project'],properties:{project:{type:'string'}}}},
 {name:'review_safe_workspace',description:'Review changes made in a CodeBridge safe workspace.',inputSchema:{type:'object',required:['project','worktree'],properties:{project:{type:'string'},worktree:{type:'string'}}}}
];
export async function callTool(name,a={}){const mode=await getAccessMode();if(!toolAllowed(name,mode))throw Object.assign(new Error(`Tool ${name} is disabled while CodeBridge is in read-only mode.`),{status:403});switch(name){case'open_workspace':return openWorkspace(a);case'list_open_workspaces':return listOpenWorkspaces();case'list_projects':return (await getConfig()).allowedRoots;case'list_files':return listWorkspace(a.path);case'read_file':return {content:await readText(a.path)};case'write_file':return writeText(a.path,a.content);case'run_command':{if(a.approvalId){const d=consumeDecision(a.approvalId,{cwd:a.cwd,executable:a.executable,args:a.args||[]});if(!d)return {approvalPending:true,approvalId:a.approvalId};if(d.status!=='approved')return {denied:true,approvalId:a.approvalId};return runStructuredCommand(a.cwd,a.executable,a.args||[],true)}const r=await runStructuredCommand(a.cwd,a.executable,a.args||[],false);if(r.approvalRequired){const q=requestApproval({type:'command',cwd:a.cwd,executable:a.executable,args:a.args||[],kind:r.kind,req:{cwd:a.cwd,executable:a.executable,args:a.args||[]}});return {approvalRequired:true,approvalId:q.id,expiresAt:q.expiresAt,kind:r.kind}}return r}case'run_legacy_shell':return runCommand(a.cwd,a.command,!!a.approved);case'git_status':return gitInfo(a.path);case'create_safe_workspace':return createSafeWorkspace(a.project);case'review_safe_workspace':return reviewSafeWorkspace(a.project,a.worktree);default:throw Object.assign(new Error(`Unknown tool: ${name}`),{status:404})}}
export function mcpResult(id,result){return {jsonrpc:'2.0',id,result}}
export async function handleMcp(msg){if(msg.method==='initialize')return mcpResult(msg.id,{protocolVersion:'2025-06-18',capabilities:{tools:{listChanged:false}},serverInfo:{name:'codebridge',version:'0.2.0-beta.3'}});if(msg.method==='notifications/initialized')return null;if(msg.method==='ping')return mcpResult(msg.id,{});if(msg.method==='tools/list'){const mode=await getAccessMode();return mcpResult(msg.id,{tools:tools.filter(t=>toolAllowed(t.name,mode))});}if(msg.method==='tools/call'){try{const data=await callTool(msg.params?.name,msg.params?.arguments||{});return mcpResult(msg.id,{content:[{type:'text',text:JSON.stringify(data)}],structuredContent:data,isError:false})}catch(e){return mcpResult(msg.id,{content:[{type:'text',text:e.message}],isError:true})}}return {jsonrpc:'2.0',id:msg.id,error:{code:-32601,message:'Method not found'}}}
